#This is the make file to execute project
cc = gcc
obj = final
all:
	$(cc) main.c rules.c welcome.c functions.h random_choice.c question1.c chose.c  question2.c question3.c question4.c question5.c question6.c question7.c question8.c question9.c question10.c -o $(obj)
exec:
	./final
clean:
	rm -rf final